---
name: Tag and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  github-actions:
    permissions:
      contents: write
    uses: martoc/workflow-github-actions/.github/workflows/github-actions.yml@v0
    secrets: inherit
